AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - vendor/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
